### PR TITLE
Fixed: Cloudflare Worker (HonoJS) Accessing R2 Files

### PR DESCRIPTION
**Pull request by aliraza556**
### Problem:
- After saving, IDEALLY, you should be able to see the updated profile picture everywhere in the app.
But, that won't happen on Dev mode.

closes: #125 

## Issue ticket number and link:
- **Ticket Number:** [ 125  ]
- **Link:** [ https://github.com/aadeshkulkarni/medium-app/issues/125 ]

### Evidence:
 - Please see the attached image as evidence.

image

### Acceptance Criteria
- [x] After saving, should be able to see the updated profile picture everywhere in the app.

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @aadeshkulkarni,
Please review this PR.

**Comment by aadeshkulkarni** [comment]
Please share a video with the following:
- The Frontend & Backend running on your local env
- User signs in, User goes to profile page, User uploads a new profile picture. 
- The profile picture gets updated at all places.

Also, show the profile picture url that is sent by the backend API to frontend.

**Comment by aliraza556** [comment]
> Please share a video with the following:
> 
> * The Frontend & Backend running on your local env
> * User signs in, User goes to profile page, User uploads a new profile picture.
> * The profile picture gets updated at all places.
> 
> Also, show the profile picture url that is sent by the backend API to frontend. (dev tools -> Network tab)

Ok

**Comment by aadeshkulkarni** [comment]
Closing due to inactivity

**Pull request closed without merging**
