### PR TITLE
Feature/end of screen message

### PR DESCRIPTION
**Pull request by Kunall-singh**
Implemented enhancement mentioned in #104 

5 animations and 5 different end-of-screen-messages which are randomly chosen at the time of showing up on the screen.

https://github.com/aadeshkulkarni/medium-app/assets/107796595/e78563cf-15b3-4e46-8c99-e33dbcb0eca5

### CODE REVIEW

**Comment by aadeshk-beam** [comment]
@Kunall-singh  - Please rebase. There are merge conflicts.

**Comment by aadeshkulkarni** [comment]
@Kunall-singh - Merge conflicts in your PR. Please fix them

**Comment by Kunall-singh** [comment]
@aadeshkulkarni Thank you for letting me know. Will make a commit soon.

**Comment by Kunall-singh** [comment]
@aadeshkulkarni All the merge conflicts has been resolved. Please let me know if anything else needed to addressed.

**Pull request merged**
