### PR TITLE
docker integration

### LINKED ISSUE #23: Refactor | Dockerize the application
Docker compose the 2 projects

- frontend 
- backend

### PR DESCRIPTION
**Pull request by SandipGyawali**
closes #23 

<hr />

docker compose file addition for the application

### CODE REVIEW

**Comment by aadeshkulkarni** [comment]
please link the relevant github-issue to the PR description.

**Comment by aadeshkulkarni** [comment]
Overall looks good. 

Just 2 pointers.
- Can you add HMR support in the docker for the frontend and backend apps ? That would really help during development.
- Add a new section for app setup using docker instructions in the readme.md file

**Comment by SandipGyawali** [comment]
yes sure

**Comment by SandipGyawali** [comment]
@aadeshkulkarni added the two points

**Pull request merged**
