### PR TITLE
Fear/thumbnail : Home page thumbnail also meta data for SEO and Dynamic thumbnail for blog page

### PR DESCRIPTION
**Pull request by t007rushi**
- Done with title, URL, image and description for thumbnail
- tested with below Screenshot attached
   - Twitter 
   - Whatsapp
   - Linkedin

Additionally set Favicon from vite to medium logo

## Before after the same link while sharing

Screenshot 2024-05-20 at 12 55 50 AM

Screenshot 2024-05-20 at 1 01 01 AM

Also can add other meta for the author and keywords

The blog page can be edited after the img section added

### CODE REVIEW

**Comment by aadeshkulkarni** [comment]
Please add a screenshot for a specific blog sharing as well

**Comment by aadeshkulkarni** [comment]
@t007rushi  - tip: You can use this chrome extension to test your meta tags without deployment locally `Localhost Open Graph Checker`

**Comment by t007rushi** [comment]
> @t007rushi - tip: You can use this chrome extension to test your meta tags without deployment locally `Localhost Open Graph Checker`

Thanks for the tips was searching the one ☺️

**Comment by aadeshkulkarni** [comment]
@t007rushi  - Any update on the `article sharing link` preview  ?

**Comment by t007rushi** [comment]
@aadeshkulkarni tried various variations for dynamic meta tag settings from the client side but most suggesting to have server-side rendering cause web crawlers don't look for js look for pre-built rendered static HTML

Tomorrow will try with backend approach for this for setting tags before load inject them before hand when call /blogs listing

**Comment by aadeshkulkarni** [comment]
@t007rushi Few client side suggestions to consider:

- [How to add meta tags for sharing particular link in ReactJS](https://stackoverflow.com/questions/60045028/how-can-i-add-meta-tags-for-sharing-a-particular-link-in-react-js)

- React Helmet is also an alternative.

**Comment by t007rushi** [comment]
Tried both react-helmet and react-helmet-async

will try first one stackoverflow post approach 👍  @aadeshkulkarni

**Comment by t007rushi** [comment]
@aadeshkulkarni tried both ways still not able to achieve this one
Pushed the code 
try if I'm missing something 

Last option is to write fs module backend induced meta tag value setting which also pushed commented in index.html

Just backend route left to write 
holding for go ahead or not?

**Comment by aadeshkulkarni** [comment]
> @aadeshkulkarni tried both ways still not able to achieve this one Pushed the code try if I'm missing something
> 
> Last option is to write fs module backend induced meta tag value setting which also pushed commented in index.html
> 
> Just backend route left to write holding for go ahead or not?

Hold on, let me give it a try

**Comment by aadeshkulkarni** [comment]
@t007rushi  - There are 7 commits on your PR at the moment. I would also urge you to squash all of the git commits into one, it will keep the commit history of the project clean. 

Here is an easy 3 min video on how to git squash commits.  [Learn Git Squash in 3 minutes](https://youtu.be/V5KrD7CmO4o?si=qIB518vnb99IIdsC)

**Comment by t007rushi** [comment]
@aadeshkulkarni  ok works

**Comment by t007rushi** [comment]
Done @aadeshkulkarni 
can you check once

**Comment by aadeshkulkarni** [comment]
@t007rushi - Looks good. However, there is a merge conflict. Please rebase

**Pull request closed without merging**
